apiVersion: v1
kind: Pod
metadata:
  name: pause-suppl-groups
  labels:
    app: pause-suppl-groups
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause
  securityContext:
    supplementalGroups:
      - 2000
