# Source: Experimental Mutating Policies from Gatekeeper Library
# https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/experimental/mutation/pod-security-policy/users/samples/mutation-supplementalGroups.yaml

apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
meta data:
  name: k8spspsupplementalgroups
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.securityContext.supplementalGroups"
  parameters:
    pathTests:
    - subPath: "spec.securityContext.supplementalGroups"
      condition: MustNotExist
    assign:
      value: [3000]